/*
 * localhost:31453
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ccp-client-go

type TypesVsphereClientConfig struct {
	Ip string `json:"ip"`
	Password string `json:"password,omitempty"`
	Port int32 `json:"port"`
	Username string `json:"username"`
}
