/*
 * localhost:31453
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ccp-client-go

type TypesKubeadm struct {
	Provider *TypesVsphereCloudProvider `json:"provider"`
	ProviderType string `json:"provider_type"`
}
