/*
 * localhost:31453
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ccp-client-go

type TypesNetworkPluginProfile struct {
	Details string `json:"details"`
	Name string `json:"name"`
	Status string `json:"status"`
}
