/*
 * localhost:31453
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ccp-client-go

type TypesNode struct {
	CloudInitData string `json:"cloud_init_data"`
	ErrorLog string `json:"error_log"`
	IsMaster bool `json:"is_master"`
	KubernetesVersion string `json:"kubernetes_version"`
	MacAddresses []string `json:"mac_addresses"`
	Name string `json:"name"`
	PrivateIp string `json:"private_ip"`
	PublicIp string `json:"public_ip"`
	State string `json:"state"`
	Template string `json:"template"`
	Uuid string `json:"uuid"`
}
