/*
 * localhost:31453
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ccp-client-go

type TypesHelmChart struct {
	ChartUrl string `json:"chart_url"`
	ClusterUUID string `json:"cluster_UUID"`
	HelmchartUuid string `json:"helmchart_uuid"`
	Name string `json:"name"`
	Options string `json:"options"`
}
