/*
 * localhost:31453
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ccp-client-go

type TypesVsphereCloudProvider struct {
	ClientConfigomitempty *TypesVsphereClientConfig `json:"client_config;omitempty"`
	VsphereClientConfigUuid string `json:"vsphere_client_config_uuid"`
	VsphereDatacenter string `json:"vsphere_datacenter"`
	VsphereDatastore string `json:"vsphere_datastore"`
	VsphereScsiControllerType string `json:"vsphere_scsi_controller_type"`
	VsphereWorkingDir string `json:"vsphere_working_dir"`
}
